### ISSUE TITLE
Trying to make an alpine image

### ISSUE THREAD

**Issue by xeor** [decred/dcrdocker#21]
I am trying to create a more lightweight version of decred using `alpine` instead of `ubuntu`.

To simplify getting it to work, I have this `Dockerfile`

```
FROM alpine:3.6

RUN apk update \
    && apk add libc6-compat curl \
    && curl -LO https://github.com/decred/decred-binaries/releases/download/v1.0.5/decred-linux-amd64-v1.0.5.tar.gz \
    && tar xzf decred-linux-amd64-v1.0.5.tar.gz
```

The `libc6-compat` library is needed because I will get an `No such file or directory` when trying to execute `decred` binaries without (because of missing `/lib64/ld-linux-x86-64.so.2`, see `readelf -a dcrwallet  | grep "Requesting program interpreter"`).

Now I am getting this error:

```
Error relocating ./dcrwallet: __vfprintf_chk: symbol not found
Error relocating ./dcrwallet: __fprintf_chk: symbol not found
```

which I think is some missing flags during the compilation.

Is there any hope getting this worked out without having to make an alpine image that compiles it all from scratch?

The absolute best and most secure docker image would be using the `scratch` base image. Something like https://blog.codeship.com/building-minimal-docker-containers-for-go-applications/, but changing from ubuntu to alpine is also good..

**Comment by jrick** [comment]
Sounds like you are trying to make a new docker image instead of modifying the existing ones (which build the projects from source instead of pulling a release).

You're right that the binaries aren't compatible on musl-based distros like alpine.  This is more or less the fault of Go, which assumes glibc.

I am ok with the idea of providing docker images for release versions running on an alpine container so if you can figure this out, please make a PR.  I think that will involve us releasing linux binaries that don't depend on glibc at all, so for testing, you will have to build these yourself since they aren't provided at the moment.

**Comment by xeor** [comment]
Yea, I'm trying to remove bloat :) I will take a look and see if I am able to make it work.. Will get back to this issue

**Comment by xeor** [comment]
I will get back to this issue if I ever do this.. Closing for now
